version: "3.1"
services:
  mario-lego:
    # we want to use the image which is build from our Dockerfile
    build: .
    ports:
      - "8080:80"
    # we mount the working dir into the container, handy for development
    volumes:
      - .:/var/www/html/
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1"
