version: "3.1"
services:
  mario-lego:
    # we want to use the image which is build from our Dockerfile
    build: .
    ports:
      - "8080:80"
    # we mount the working dir into the container, handy for development
    volumes:
      - ./src:/var/www/html/
